[package]
name = "search-and-destroy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
num_cpus = "1.15.0"
sha256 = "1.1.3"
tokio = "1.28.1"
